### PR TITLE
Add new DynamoDB tool

### PR DESCRIPTION
**Pull request by whimzyLive**
# Changes

- add TypeDORM to the tool

### CODE REVIEW

**Comment by whimzyLive** [comment]
@alexdebrie what do you think about this addition?

**Comment by alexdebrie** [comment]
Looks cool, @whimzyLive ! Thanks for sharing.

Could you move it to the end of the `Tools` section? The first few on there are ones I have experience with and endorse, while the other libraries I have less experience with.

**Comment by whimzyLive** [comment]
@alexdebrie Okay makes sense. Updated.

**Comment by alexdebrie** [comment]
Thank you!

**Pull request merged**
