### PR TITLE
[WIP-Feat]: Add 'Uses' Section to Showcase DynamoDB Extensibility w/ Concrete Examples

### PR DESCRIPTION
**Pull request by medelman17**
DynamoDB's scalability is, perhaps, rivaled only by its equally impressive extensibility. This PR seeks to establish a home for the many excellent resources scattered around the web that showcase dynamo in 'near-concrete' applications. 

It is anticipated that the addition of this section would, inter alia, serve: (1) as a reference point for those already working with dynamo; and (2) as a source of inspiration for those exploring the possibility of doing the same.

### CODE REVIEW

**Comment by alexdebrie** [comment]
Great idea! Thanks for gathering these, @medelman17

**Comment by alexdebrie** [comment]
Also, just saw you had it marked as WIP :) Sorry about that. If you have others that you want to gather, feel free to pull together as a different PR and I'll hold off until you're ready.

**Comment by medelman17** [comment]
Ha! No worries, @alexdebrie. I do have more; so, will open up another one. :-) What's best format for you to review? Individual article additions as atomic commits in one overarching PR?

**Comment by alexdebrie** [comment]
@medelman17 Whatever is easiest for you! Since it's a content repo, I think I'm indifferent to one big one or many small ones.  :)

**Review by miatska — COMMENTED** [review]
🤍

**Pull request merged**
